### ISSUE TITLE
Can't install with pip

### ISSUE THREAD

**Issue by ayeganov** [cloudbase/PyMI#30]
Setup.py relies on gitpython being installed to install PyMI:

> Collecting PyMI
>   Using cached PyMI-1.0.4.zip
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\AYEGAN~1.SYM\AppData\Local\Temp\pip-build-nrog9ome\PyMI\setup.py", line 1, in <module>
>         import git
>     ImportError: No module named 'git'

After installing "gitpython" setup.py still fails:

> Collecting PyMI
>   Using cached PyMI-1.0.4.zip
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\AYEGAN~1.SYM\AppData\Local\Temp\pip-build-q9p3q46t\PyMI\setup.py", line 17, in <module>
>         version=get_git_version(),
>       File "C:\Users\AYEGAN~1.SYM\AppData\Local\Temp\pip-build-q9p3q46t\PyMI\setup.py", line 8, in get_git_version
>         return g.describe(tags=True)
>       File "c:\program files\python35\lib\site-packages\git\cmd.py", line 424, in <lambda>
>         return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
>       File "c:\program files\python35\lib\site-packages\git\cmd.py", line 873, in _call_process
>         return self.execute(call, **_kwargs)
>       File "c:\program files\python35\lib\site-packages\git\cmd.py", line 687, in execute
>         raise GitCommandError(command, status, stderr_value, stdout_value)
>     git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
>       cmdline: git describe --tags
>       stderr: 'fatal: Not a git repository (or any of the parent directories): .git'

**Comment by americanhanko** [comment]
Same here.

**Comment by alexpilotti** [comment]
In this case pip is trying to build from sources instead of using a binary wheel. beside going to fix this, we're also going to release wheels for Python 3.5 and 3.6.

**Comment by alexpilotti** [comment]
@ayeganov @americanhanko Added a wheel for Python 3.5 x64, can you please test if pip install works for you now?

**Comment by ayeganov** [comment]
All good now! Thank you for the fix.

**Comment by revizor1** [comment]
Any fix for 3.6 x64 yet?

**Comment by alexpilotti** [comment]
@revizor1 just added wheels for 3.6 (both amd64 and win32), please let us know if you have any issues.

**Comment by revizor1** [comment]
Thank you so much!

**Comment by alexpilotti** [comment]
@revizor1 thanks for getting back, closing this issue.

**Comment by blakerouse** [comment]
Can you add a wheel for 2.7 (if possible) and 3.3?

As cloudbase-init uses py27 and py33 in its tox.ini. This branch for cloudbase-init for MAAS custom networking https://github.com/ader1990/cloudbase-init/blob/advanced_networking/requirements.txt#L16 adds it as a requirement, which fails using tox because "import git" fails like above.

**Comment by alexpilotti** [comment]
@blakerouse there are Windows 2.7 wheels (both x86 and x64), and also 3.4, 3.5, 3.6:
https://pypi.python.org/pypi/PyMI/1.0.4

Unit tests (Linux) still use 3.3 (see https://review.openstsck.org).

**Comment by codingadvocate** [comment]
I've hit the same issue on Windows for Python 3.7.1.  No problems on 3.6.1 or 3.6.5 using the same pyMi v1.0.4, but I'm hitting the issue in testing for migration to 3.7.  Nothing critical at this point, more a forward looking question.

And thank you for the great work!

**Comment by alexpilotti** [comment]
Hi, the reason is that we need to publish wheels for python 3.7

**Comment by macabees** [comment]
Same problem, PyMI is not working with Python 3.7.x

**Comment by anshulxyz** [comment]
getting this error for Python3.8 on Windows

**Comment by ader1990** [comment]
@anshulxyz You should be able to use github actions to build PyMI with no problems. https://github.com/cloudbase/PyMI/pull/44/files

**Comment by satymaju** [comment]
hi,
getting the same error with python 3.8 and wheel 0.34.2.
Any solution guys ?

**Comment by ader1990** [comment]
> hi,
> getting the same error with python 3.8 and wheel 0.34.2.
> Any solution guys ?

Hello. You have the solution in my previous comment. The latest pypi version has not been updated since a while (2016).

**Comment by satymaju** [comment]
@ader1990 It is not clear, what you want me to do. Can you please elaborate.
I tried to install it with pip install PyMI.

**Comment by ader1990** [comment]
> @ader1990 It is not clear, what you want me to do. Can you please elaborate.
> I tried to install it with pip install PyMI.

The PyMI code on pypi is obsolete and does not work with pip install. The code from this repository is the latest one, which works with pip install. You can either build PyMI using my instructions above or you can directly run: **pip install git+https://github.com/cloudbase/PyMI**
