### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by fbe-work** [cloudbase/PyMI#32]
after a flawless 
```python
pip install pyMI
```
install on my win7 python 3.6.2 I get "Successfully installed pyMI-1.0.4". however when I try to "import mi" in the python REPL it gives me this error:
```
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]
 on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\mi\__init__.py", line 1, in
<module>
    from .mi import *  # nopep8
ImportError: DLL load failed: The specified module could not be found.
```
in the directory of `__init__.py` there are only:
```
__pycache__
__init__.py
mi.pdb
mi.pyd
```
do you know which DLL it is searching?
Thank you!

**Comment by claudiubelu** [comment]
Hi,

It's probably missing mi.dll, which is mandatory for this library. It seems that Windows 7 doesn't come with it normally. I've replicated the issue, and after installing Windows Management Framework 4.0 (Windows6.1-KB2819745-x64-MultiPkg.msu), it worked.

Best regards,

Claudiu Belu

**Comment by fbe-work** [comment]
Hi @bclau , thank you so much! 
After installing the MultiPkg it works like charm!!
Best, hdm-dt-fb
