### ISSUE TITLE
Wheel for Python 3.8

### ISSUE THREAD

**Issue by ader1990** [cloudbase/PyMI#43]
Python 3.8 has been released in Oct 2019, do you plan to create wheels for it?
https://www.python.org/dev/peps/pep-0569/#lifespan

**Comment by codingadvocate** [comment]
Hi Adrian,

 

Actually, the fact that Twisted wheels are being generated on Windows now is AWESOME.  Thanks community!

 

I haven’t personally installed Python 3.8 yet.  But if I’m reading the article you shared correctly, it indicates the planned Python 3.8 release date was projected for Oct 14th of this year (two weeks ago).  And the python.org website confirms this with an entry in the “latest news” section that mentions “Python 3.8.0 is now available” on the same date.

 

-Chris
